In [1]:
# # !pip list
# !pip install sqlalchemy
# !pip install psycopg2-binary

In [2]:
import pandas as pd
import numpy as np
import os
import sqlite3
from sqlalchemy import create_engine

In [3]:
# Define the path to the 'pythonproject' inside the 'Panda Data' folder
desktop = os.path.expanduser("~/Desktop")
panda_data_folder = os.path.join(desktop, "Panda Data", "pythonProject1", '.venv')

# Make sure the 'pythonproject' folder exists
os.makedirs(panda_data_folder, exist_ok=True)

# Path for the SQLite database file inside the 'pythonproject' folder
database_path = os.path.join(panda_data_folder, "mydatabase10.sqlite")

# Create an SQLite database engine at the specified path
engine = create_engine(f'sqlite:///{database_path}')

In [4]:
df = pd.read_csv ('TEST Backup.csv', encoding='Latin-1') 
employ_df = pd.read_csv ('TEST Backup.csv', encoding='Latin-1', index_col = 'employee_name') 
# index_col = 'employee_name' make it so its the index(The number on the left side)

In [5]:
pd.set_option('display.max_columns', 172)
pd.set_option('display.max_rows', 10000)

#df.head(4)

In [6]:
#df.tail(4)

In [7]:
# df[['employee_name','years_of_experience','regional_years_of_experience']]
# df[['employee_name','years_of_experience','regional_years_of_experience']]

In [8]:
#df[['position']]
# df.columns

In [9]:
# df[df['duties_2']=='\n']

In [10]:
# Same results (iloc and loc)

# df.loc[[0,2,4],['marital_status','driving_license']]
# df.iloc[[0,2,4],[7,8]]
# df.columns
#df['duties_2'].value_counts(dropna=False)
# df.loc[0:9,'employee_name':'position']    # don;t need to type out all columns

In [11]:
#df.set_index('years_with_dorsch') # Make it permanent with inplace = True || Example: df.set_index('years_with_dorsch', inplace = True)

In [12]:
#employ_df.loc['Waleed Mohamed Saber Mohamed Sarhan']

In [13]:
#employ_df.sort_index()

In [14]:
#filt = (df['years_of_experience'] == 27)

In [15]:
# df[filt]
#df.loc[filt,'employee_name']

In [16]:
#df.loc[filt, 'employee_name': 'position']

In [17]:
countries = ['United States','India','Qatar','UAE','Egypt']
countryFilt = df['education_country_1'].isin(countries)

In [18]:
#df.loc[countryFilt,'education_country_1'].tail(20)

In [19]:
#positionFilt = df['position'].str.contains('neer', na = False)

In [20]:
#df.loc[positionFilt,'position'].head(20)

In [21]:
#positionFilt

In [22]:
#employInfo = df.loc[1:200,'employee_name':'languages']

In [23]:
#employInfo.head(3)

In [24]:
# df.columns = [x.lower()for x in df.columns]
# df.head(2)

#makes all the columns upper cases or lower cases, can also be used to replace space with _

In [25]:
# df.loc[2].head(5)

In [26]:
# df.insert(0, 'employee_id', range(len(df)))

In [27]:
# df.tail(10)

In [28]:
# df.drop(columns = 'employee_id').head(5)

In [29]:
#df.drop_duplicates()

In [30]:
#df['employee_name'].value_counts()

In [31]:
filt = (df['employee_name'] == 'Ibrar Ahmad')
df.loc[filt]

,employee_name,years_of_experience,regional_years_of_experience,years_with_dorsch,position,dob,nationality,marital_status,driving_license,languages,education_date_1,education_name_of_institution_1,education_country_1,education_date_2,education_name_of_institution_2,education_country_2,education_date_3,education_name_of_institution_3,education_country_3,memberships,key_qualifications,professional_training,name_current_employer,address_current_employer,telephone,fax,email,job_title,year_current,contact_reference,from_1,to_1,pos_1,employer_1,project_1,country_1,duties_1,from_2,to_2,pos_2,employer_2,project_2,country_2,duties_2,from_3,to_3,pos_3,employer_3,project_3,country_3,duties_3,from_4,to_4,pos_4,employer_4,project_4,country_4,duties_4,from_5,to_5,pos_5,employer_5,project_5,country_5,duties_5,from_6,to_6,pos_6,employer_6,project_6,country_6,duties_6,from_7,to_7,pos_7,employer_7,project_7,country_7,duties_7,from_8,to_8,pos_8,employer_8,project_8,country_8,duties_8,from_9,to_9,pos_9,employer_9,project_9,country_9,duties_9,from_10,to_10,pos_10,employer_10,project_10,country_10,duties_10,from_11,to_11,pos_11,employer_11,project_11,country_11,duties_11,from_12,to_12,pos_12,employer_12,project_12,country_12,duties_12,from_13,to_13,pos_13,employer_13,project_13,country_13,duties_13,from_14,to_14,pos_14,employer_14,project_14,country_14,duties_14,from_15,to_15,pos_15,employer_15,project_15,country_15,duties_15,from_16,to_16,pos_16,employer_16,project_16,country_16,duties_16,from_17,to_17,pos_17,employer_17,project_17,country_17,duties_17,from_18,to_18,pos_18,employer_18,project_18,country_18,duties_18,from_19,to_19,pos_19,employer_19,project_19,country_19,duties_19,from_20,to_20,pos_20,employer_20,project_20,country_20,duties_20,Date Created,Date Updated
26,Ibrar Ahmad,10.0,NaN,NaN,Document Controller,1983,Pakistani,Married,NaN,"English, Urdu and Pashto",-,Master of Science & Information & Technology (...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10 years of experience in documentation with M...,ACONEX \nSEO\nGraphics designing\n,Al Sarh Trading & Contracting Qatar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19-Sep,Till Date,Document Controller,Al Sarh Trading & Contracting,Al Meshaf Package 4,NaN,Managing and monitoring day-by-day electronic ...,24-Jul,24-Jul,Document Control Officer & Coordinator,Ghantoot Group Roads Division,Development of South Shamkha Lot-1,UAE,Working as Corporate Senior Document Controlle...,8-Jun,12-Jun,Network Support Engineer,FiDES Technology Private Limited,Computerization of Pakistan post office,Pakistan,Installation & configuration of LAN (both Cabl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,Ibrar Ahmad,13.0,NaN,NaN,Lead Document Controller,1983,Pakistani,Married,NaN,English and Urdu,NaN,Master of science & Information & Technology (...,Paksitan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13 years of experience in documentation with M...,ACONEX \nSEO\nGraphics designing\n,Al Sarh Trading & Contracting,Qatar,NaN,NaN,NaN,NaN,2,NaN,19-Sep,Till date,Document Controller,Al Sarh Trading & Contracting,Al Meshaf Package 4,Qatar,Managing and monitoring day-by-day electronic ...,24-Jul,24-Jul,Document Control Officer & Coordinator,Ghantoot Group Roads Division,Development of South Shamkha Lot-1,UAE,Working as Corporate Senior Document Controlle...,8-Jun,12-Jun,Network Support Engineer,FiDES Technology Private Limited,Computerization of Pakistan post office,Pakistan,Installation & configuration of LAN (both Cabl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
238,Ibrar Ahmad,13.0,NaN,NaN,Secretary,1983,Pakistani,Married,NaN,"English, Urdu and Pashto",NaN,Master of science & information & technology (...,Pakistan,NaN,\n,NaN,NaN,\n,NaN,-\n,10 years of experience in documentation with M...,ACONEX \nSEO\nGraphics designing\nMicrosoft Ex...,Al Sarh Trading & Contracting Qatar,"Alsarh Holding Group, D Ring Rd, Doha, Qatar",+974 4462 1886,NaN,NaN,Document Controller,2,NaN,2019,Till date,Document Controller,Al Sarh Trading & Contracting Qatar,Al Meshaf Package 4.\n\n,NaN,Managing and monitoring day-by-day electronic ...,5-Jul,5-Jul,Document Control Officer & Coordinator,Ghantoot Group Roads division UAE Abu Dhabi,Development of South Shamkha Lot-1\n\n,NaN,Working as Corporate Senior Document Controlle...,2008,2012,Network Support Engineer,"FiDES Technology Private Limited - Islamabad, ...",Computerization of Pakistan post office\n\n,NaN,Installation & configuration of LAN (both Cabl...,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,23-02-2021 at 4:59:09 PM,NaN
413,Ibrar Ahmad,13.0,NaN,NaN,Document controller-Administration,1983,Pakistani,Married,NaN,"English, Urdu and Pashto",NaN,Master of science & information & technology (...,NaN,NaN,\n,NaN,NaN,\n,NaN,-\n,10 years of experience in documentation with M...,Setting up Document Numbering & Filing systems...,Al Sarh Trading & Contracting Qatar,NaN,NaN,NaN,NaN,Document Controller,2,NaN,2019,Till date,Document Controller,Al Sarh Trading & Contracting Qatar,Al Meshaf Package 4\n,NaN,Managing and monitoring day-by-day electronic ...,5-Jul,5-Jul,Document Control Officer & Coordinator,Ghantoot Group Roads division UAE Abu Dhabi,Development of South Shamkha Lot-1\n,NaN,Working as Corporate Senior Document Controlle...,2008,2012,Network Support Engineer,"FiDES Technology Private Limited - Islamabad, ...",Computerization of Pakistan post office\n,NaN,Installation & configuration of LAN (both Cabl...,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,31-03-2021 at 05:16:06 PM,NaN

In [32]:
df.shape

(1420, 172)

In [33]:
df_sort = df.sort_values(by=['employee_name', 'email'], na_position='last')
df_sort['email'] = df_sort['email'].fillna('placeholder')
df_sort['employee_name'] = df['employee_name'].str.strip()
df_sort['email'] = df['email'].str.strip()
df_sort['email'] = df['email'].str.rstrip("\n")
df_sort['email'] = df['email'].str.lstrip("\n")
df_sort = df[df['email'].str.contains('@', na=False) | df['email'].isna()]

In [34]:
df_unique = df_sort.drop_duplicates(subset=['employee_name', 'email'], keep='last')
df_unique.loc[df_unique['email'] == 'placeholder', 'email'] = pd.NA

In [35]:
#df_unique['telephone'].value_counts()

In [36]:
df_unique['employee_name'].value_counts().head(20)

employee_name
Usman Fazal                       2
Subin Ninan Alex                  2
Mohammad Yaqoob Khojah            2
Edward Gates                      2
Mudassir Ahmed                    2
Dan Diaconu                       2
Shinoj Vaniyathur                 2
Mahmoud Mohamed Abdel Hamid       2
Shahnawaz Pasha                   1
Joseph D. Velasco                 1
Hani Sayed Ibrahim Mostafa        1
Zuhair Younes Al Amour            1
Hesham MOSTAFA MOHAMED IBRAHIM    1
Zia ur Rahman                     1
Mohamad javid Talikoti            1
Emad Zaki Abdeljawad              1
Ali Elhamzawy                     1
Mohammed Abrar                    1
ABDULLA KM                        1
Muhammad Adeel Qureshi            1
Name: count, dtype: int64

In [37]:
df_unique.replace('-',np.nan, inplace=True)

C:\Users\Sharmarke.Kadir\AppData\Local\Temp\ipykernel_28924\4158826778.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unique.replace('-',np.nan, inplace=True)

In [38]:
# filt = (df_unique['email'] == 'maria.wilma@dorsch.com')
# filt = (df_unique['telephone'] == '9.72E+11')
filt = (df_unique['employee_name'] == 'Maria')
df_unique.loc[filt]

Empty DataFrame
Columns: [employee_name, years_of_experience, regional_years_of_experience, years_with_dorsch, position, dob, nationality, marital_status, driving_license, languages, education_date_1, education_name_of_institution_1, education_country_1, education_date_2, education_name_of_institution_2, education_country_2, education_date_3, education_name_of_institution_3, education_country_3, memberships, key_qualifications, professional_training, name_current_employer, address_current_employer, telephone, fax, email, job_title, year_current, contact_reference, from_1, to_1, pos_1, employer_1, project_1, country_1, duties_1, from_2, to_2, pos_2, employer_2, project_2, country_2, duties_2, from_3, to_3, pos_3, employer_3, project_3, country_3, duties_3, from_4, to_4, pos_4, employer_4, project_4, country_4, duties_4, from_5, to_5, pos_5, employer_5, project_5, country_5, duties_5, from_6, to_6, pos_6, employer_6, project_6, country_6, duties_6, from_7, to_7, pos_7, employer_7, project_7, country_7, duties_7, from_8, to_8, pos_8, employer_8, project_8, country_8, duties_8, from_9, to_9, pos_9, employer_9, project_9, country_9, duties_9, from_10, to_10, pos_10, employer_10, project_10, country_10, duties_10, ...]
Index: []

In [39]:
# df_unique['employee_name'].value_counts()
# df_unique['email'].value_counts()

In [40]:
DFrows = df_unique.shape[0]
DFcolumns = df_unique.shape[1]

print(f"rows = {DFrows} and columns = {DFcolumns}")

rows = 1336 and columns = 172

In [64]:
df_unique.drop(columns = 'employee_id', inplace = True)

C:\Users\Sharmarke.Kadir\AppData\Local\Temp\ipykernel_28924\688878331.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_unique.drop(columns = 'employee_id', inplace = True)

In [65]:
df_unique.columns

Index(['employee_name', 'years_of_experience', 'regional_years_of_experience',
       'years_with_dorsch', 'position', 'dob', 'nationality', 'marital_status',
       'driving_license', 'languages',
       ...
       'duties_19', 'from_20', 'to_20', 'pos_20', 'employer_20', 'project_20',
       'country_20', 'duties_20', 'Date Created', 'Date Updated'],
      dtype='object', length=172)

In [66]:
# adding an employee ID(Error will appear if asked to create a column that already exists)
df_unique.insert(0, 'employee_id', range(len(df_unique)))
# removing rows with only NaN
df.dropna(axis = 'index', how = 'all').head(5)

,employee_name,years_of_experience,regional_years_of_experience,years_with_dorsch,position,dob,nationality,marital_status,driving_license,languages,education_date_1,education_name_of_institution_1,education_country_1,education_date_2,education_name_of_institution_2,education_country_2,education_date_3,education_name_of_institution_3,education_country_3,memberships,key_qualifications,professional_training,name_current_employer,address_current_employer,telephone,fax,email,job_title,year_current,contact_reference,from_1,to_1,pos_1,employer_1,project_1,country_1,duties_1,from_2,to_2,pos_2,employer_2,project_2,country_2,duties_2,from_3,to_3,pos_3,employer_3,project_3,country_3,duties_3,from_4,to_4,pos_4,employer_4,project_4,country_4,duties_4,from_5,to_5,pos_5,employer_5,project_5,country_5,duties_5,from_6,to_6,pos_6,employer_6,project_6,country_6,duties_6,from_7,to_7,pos_7,employer_7,project_7,country_7,duties_7,from_8,to_8,pos_8,employer_8,project_8,country_8,duties_8,from_9,to_9,pos_9,employer_9,project_9,country_9,duties_9,from_10,to_10,pos_10,employer_10,project_10,country_10,duties_10,from_11,to_11,pos_11,employer_11,project_11,country_11,duties_11,from_12,to_12,pos_12,employer_12,project_12,country_12,duties_12,from_13,to_13,pos_13,employer_13,project_13,country_13,duties_13,from_14,to_14,pos_14,employer_14,project_14,country_14,duties_14,from_15,to_15,pos_15,employer_15,project_15,country_15,duties_15,from_16,to_16,pos_16,employer_16,project_16,country_16,duties_16,from_17,to_17,pos_17,employer_17,project_17,country_17,duties_17,from_18,to_18,pos_18,employer_18,project_18,country_18,duties_18,from_19,to_19,pos_19,employer_19,project_19,country_19,duties_19,from_20,to_20,pos_20,employer_20,project_20,country_20,duties_20,Date Created,Date Updated
0,-,NaN,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-,-,-,-,NaN,-,-,-,-,-,-,NaN,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-,-,-,-,NaN,-,-,-,-,-,-,NaN,-,-,-,-,-,-,NaN,-,-,-,-,-,-,NaN,-,-,-,-,-,-,NaN,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN
1,"Pablo Ageas, Jr.",18.0,NaN,NaN,Safety Engineer,1979,Filipino,Married,NaN,"English, Filipino, Arabic, Spanish",2008,Bachelor of Laws,NaN,2002,Bachelor of Science in Business Management,NaN,1996,Bachelor of Science in Management Accounting,NaN,NaN,NaN,"NEBOSH,\n OSHA,\n IOSH Managing Safely, \n CF...",Arcadis consulting,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,Present,HSE Lead,Arcadis Consulting,Construction of Container Terminal 2 in Hamad ...,NaN,Drive the project to start/kick-off (kick-off ...,24-Oct,24-Nov,Sr. HSE Engineer,Arcadis Consulting,Local Roads and Drainage Program (LRDP) and Ro...,NaN,Review contractorâs OHS Plan and MSRA.\nSmal...,13-Jul,14-Sep,HSE Manager,SL Engineering and Contruction (SKEC),Project: Booster Station 132 and enhancements ...,NaN,NaN,11-Jun,13-Jun,Project HSSE Manager,Nael and Bin Harmal Hydroexpert (NBHH),NaN,NaN,Promote and encourage high level of HSE awaren...,9-Nov,11-May,Project HSE Manager,NBHH,Diversion Roads and Villa,NaN,Assist the Project Director in making plans an...,8-Mar,9-Oct,HSE Engineer,NBHH,"Yas Island Development (Pipe Laying, Pumping S...",NaN,Strict monitoring and supervision to all safet...,6-Jan,9-Oct,HSE Officer,NBHH,Construction of TSE Line from Sewerage Treatme...,NaN,Ensures PTW compliance. \nConduct Toolbox Talk...,2-Apr,5-Nov,Project Consultant,Local Government Unit (LGU),Government Sector,NaN,Assess the feasibility of Government projects ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Waleed Mohamed Saber Mohamed Sarhan,23.0,NaN,NaN,Senior Architect,1974,Egyptian,Married,NaN,Arabic & English,1997,Bachelor of Science -Architectural Engineering...,Egypt,NaN,NaN,NaN,NaN,NaN,NaN,Registered Member of Egyptian Syndicate of Eng...,"A highly self-motivated, focused, innovated an...",-,DORSCH GRUPPE Middle East â Qatar,Qatar / Doha,NaN,NaN,NaN,Project Manager,NaN,NaN,16-Jun,Till date,Project Manager,DORSCH GRUPPE Middle East â Qatar,ASAS Marina Towers \nMANATEQ Oasis Bldg. Ras B...,NaN,Representing as PMCM Sr. RE with full coordina...,24-Feb,24-Jun,Project Manager,PRIVATE ENGINEERING OFFICE- Qatar,Al Daayen Complex Hall \nAl Wakra Old Souq \nH...,NaN,Leading and directing all construction stages ...,11-Jun,15-Feb,Project Manager,Engineering Consultants Group - Qatar,SAMARIYA Twin Towers: a High rise building loc...,NaN,Leading the project construction planning in e...,10-May,11-May,Resident Engineer,Ehaf Consultancy - Egypt,"Palm Hill City Mall in Cairo, Egypt",NaN,Providing construction input to have an accept...,7-Dec,10-Apr,Resident Engineer / Architect,HAZ INTERNATIONAL â UAE,"Ritz Carlton Hotel Dubai, UAE \nWhite Square O...",NaN,Identify the scope of work and disseminate it ...,2-May,7-Nov,Design Leader,Ewan Consultancy â UAE,"87 Villas & Compound for First Gulf Bank, Abu ...",NaN,Preparing IFC drawings complying with project ...,Oct-97,2-Jan,Architect,AMECO â Egypt,"SOLIMANIA Golf Village, Alex Cairo Road, 1038 ...",NaN,Supervision Site Engineer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Aly AbdelMonem Abdelhalim,16.0,NaN,NaN,Senior Planning Engineer,1982,Egyptian,Married,NaN,Arabic and English,2003,B.Sc. Civil Engineering,Egypt,NaN,NaN,NaN,NaN,NaN,NaN,"PMPÂ® # 1424401, Jul 2011, PMI, USA\n PMI-SPÂ...",has 16 years of experience in planning and sch...,Oracle - Primavera P6 Professional.\n AutoCAD...,AECOM Middle East Ltd,Qatar,NaN,NaN,NaN,NaN,NaN,NaN,16-Oct,Present,Senior Planning Engineer,NaN,"LRDP, Contract 02 (Qatar South), QS036\nLRDP, ...",Qatar,Using Primavera P6 Professional for monitoring...,24-Apr,24-Oct,Senior Planning Engineer,NaN,Construction of Residential Compound 70 Villas...,Qatar,Define project scope of work; Established Prel...,11-Aug,14-Apr,Planning Engineer,DIAACONSULT for Engineering & Consulting,SAMA ASWAN Commercial and Residential Complex ...,Egypt,Collect and review the contract documents to d...,7-Dec,11-Aug,Assistant Resident Engineer,DR. M. H. ALI El-SAIE Consulting Engineers,Supply and Installation of 3.3 US MGD SWRO Pl...,UAE,Inspection of civil work at site as per the â...,6-Mar,7-Dec,Project Site Engineer,SPARTAN Trading and Contracting Co,"Holiday Villa Hotels Series on an area of 20,0...",Qatar,Direct and manage the execution of civil work ...,4-Jan,6-Mar,Junior Civil Engineer,Ministry of Transportation,Construction of Arterial Road in East Port Sai...,Egypt,"Reviewing all project documents, drawings, met...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Vijayakumar Sadaiyan,19.0,NaN,NaN,Senior Safety Inspector,1983,Indian,Married,NaN,Urdu & english,2016,Bachelor of Science in Fire & Industrial Safet...,India,2000,National trade diploma certificate in Electric...,India,NaN,\n,NaN,GradIosh (Membership no. 218510)\n,A span of 15+ years of professional experience...,NVQ Level 6 Diploma - Shields U.K.\nNEBOSH IGC...,"Dorsch Gruppe, Qatar",Qatar,NaN,NaN,NaN,Sr.Safety Inspector,1,NaN,2021,Till date,Sr.Safety Inspector,"Dorsch Gruppe, Qatar",Roads & Infrastructure in the south of Al-Mesh...,NaN,\n,5-Jul,5-Jul,OHSS Manager,"Al Sarh, Trading & Contracting W.L.L, Qatar",Roads & Infrastructure in the south of Al-Mesh...,NaN,\n,2014,2020,PHSE Engineer/Dy.HSE Manager,"Al Bandary Engineering, Trading & Contracting ...","Sahara tower-P115 (3B+M+38F)-, Al Shahad Tower...",NaN,Reporting to Project manager & D.HSE Corp.Mana...,11-Jun,14-Mar,Sr.Safety Officer/Site In Charge,Power line engineering-Qatar W.L.L,"Viva Baharia (VB20&21)-2P+23+4R+Dome, Pearl Qa...",NaN,\n,11-May,11-Jun,PHSE In Charge,"CEC International Corporation, India","TBM-01, UG-02 project. (Majestic â Chinnasam...",NaN,\n,9-Apr,10-Apr,Sr.Safety Officer,Power line engineering-Qatar W.L.L,"Medina central, Pearl Qatar project, Doha. (8 ...",NaN,\n,2008,2009,Sr.Tunnel Safety Officer,"JT METRO (Kori con. Dubai Branch, UAE",TBM 1-2 Alras Station â Burjuman Station- Du...,NaN,\n,5-Mar,7-Jul,Site Supervisor Cum Safety Supervisor,"Kori construction (S) Pte. Ltd, Singapore","C-823 Circle Stage 2 Project, Paya Lebar Inter...",NaN,\n,4-Mar,5-Feb,Safety Supervisor Cum Lifting Supervisor,"Kori construction (S) Pte. Ltd, Singapore","C-823 Circle Stage 2 Project, Old Airport Road...",NaN,\n,3-Jun,4-Feb,Safety Supervisor,"Kori construction (S) Pte. Ltd, Singapore","824 Circle Stage 1 Project, Nichol Highway sta...",NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,18-03-2022 at 04:14:20 PM

In [67]:
# df_unique['employee_id']

In [68]:


# Select the missing columns
missing_columns = df_unique.loc[1:DFrows, ['employee_id','email', 'telephone']]

# Select the desired range of rows and columns
employeeInformation = df_unique.loc[1:DFrows, 'employee_name':'languages']

# Concatenate the DataFrames along the columns
employeeInformation = pd.concat([employeeInformation, missing_columns], axis=1)
employeeInformation.tail(5)

,employee_name,years_of_experience,regional_years_of_experience,years_with_dorsch,position,dob,nationality,marital_status,driving_license,languages,employee_id,email,telephone
1332,Ayman Abduhalim Abdurahman,22.0,NaN,NaN,Mechanical Engineer,1974,Egyptian,Married,Yes,English Arabic,1252,ayman61050@gmail.com,9.67E+11
1333,MUHAMMED JASEEM,11.0,NaN,NaN,Document Controller,1989,Indian,Married,NaN,"English, Arabic Hindi, Tamil and Malayalam",1253,NaN,NaN
1334,Ahmed Abdelraof Ahmed Shahen,30.0,NaN,NaN,Contracts Director,1970,Egyptian,Married,NaN,"Arabic, English",1254,NaN,NaN
1335,MED MOHAMED AMIN,17.0,NaN,NaN,Site Electrical Engineer,1983,EGYPTIAN,Married,NaN,Arabic English,1255,NaN,NaN
1336,MOHAMMED ABDUL WAHEED,16.0,NaN,NaN,Document Control Specialist,1971,Indian,Married,Yes,"Arabic, English, Urdu",1256,NaN,NaN

In [69]:
employeeEducation = df_unique.loc[1:DFrows,'education_date_1':'professional_training']
missing_columns = df_unique.loc[1:DFrows, ['employee_id']]
employeeEducation = pd.concat([employeeEducation, missing_columns], axis=1)
employeeEducation.head()

,education_date_1,education_name_of_institution_1,education_country_1,education_date_2,education_name_of_institution_2,education_country_2,education_date_3,education_name_of_institution_3,education_country_3,memberships,key_qualifications,professional_training,employee_id
1,2008,Bachelor of Laws,NaN,2002,Bachelor of Science in Business Management,NaN,1996,Bachelor of Science in Management Accounting,NaN,NaN,NaN,"NEBOSH,\n OSHA,\n IOSH Managing Safely, \n CF...",0
2,1997,Bachelor of Science -Architectural Engineering...,Egypt,NaN,NaN,NaN,NaN,NaN,NaN,Registered Member of Egyptian Syndicate of Eng...,"A highly self-motivated, focused, innovated an...",NaN,1
3,2003,B.Sc. Civil Engineering,Egypt,NaN,NaN,NaN,NaN,NaN,NaN,"PMPÂ® # 1424401, Jul 2011, PMI, USA\n PMI-SPÂ...",has 16 years of experience in planning and sch...,Oracle - Primavera P6 Professional.\n AutoCAD...,2
4,2016,Bachelor of Science in Fire & Industrial Safet...,India,2000,National trade diploma certificate in Electric...,India,NaN,\n,NaN,GradIosh (Membership no. 218510)\n,A span of 15+ years of professional experience...,NVQ Level 6 Diploma - Shields U.K.\nNEBOSH IGC...,3
5,2000,"Diploma in Project Management, American Univer...",Egypt,1998,Primary Studies for Master in Structural Analy...,Egypt,1993,"Bachelorâs Degree in Civil Engineering, Zaga...",Egypt,Qatar Municipality Grade A [2012] Date of Cer...,With comprehensive of 26 years knowledge and ...,\n\n\n,4

In [70]:
# Select the desired range of rows and columns
employeeExperience = df_unique.loc[1:DFrows, 'name_current_employer':'duties_20']
missing_columns = df_unique.loc[1:DFrows, ['employee_id']]

# Drop the 'email' and 'telephone' columns if they exist in the selection
employeeExperience = employeeExperience.drop(columns=['email', 'telephone'], errors='ignore')
employeeExperience = pd.concat([employeeExperience, missing_columns], axis=1)

employeeExperience.head()

,name_current_employer,address_current_employer,fax,job_title,year_current,contact_reference,from_1,to_1,pos_1,employer_1,project_1,country_1,duties_1,from_2,to_2,pos_2,employer_2,project_2,country_2,duties_2,from_3,to_3,pos_3,employer_3,project_3,country_3,duties_3,from_4,to_4,pos_4,employer_4,project_4,country_4,duties_4,from_5,to_5,pos_5,employer_5,project_5,country_5,duties_5,from_6,to_6,pos_6,employer_6,project_6,country_6,duties_6,from_7,to_7,pos_7,employer_7,project_7,country_7,duties_7,from_8,to_8,pos_8,employer_8,project_8,country_8,duties_8,from_9,to_9,pos_9,employer_9,project_9,country_9,duties_9,from_10,to_10,pos_10,employer_10,project_10,country_10,duties_10,from_11,to_11,pos_11,employer_11,project_11,country_11,duties_11,from_12,to_12,pos_12,employer_12,project_12,country_12,duties_12,from_13,to_13,pos_13,employer_13,project_13,country_13,duties_13,from_14,to_14,pos_14,employer_14,project_14,country_14,duties_14,from_15,to_15,pos_15,employer_15,project_15,country_15,duties_15,from_16,to_16,pos_16,employer_16,project_16,country_16,duties_16,from_17,to_17,pos_17,employer_17,project_17,country_17,duties_17,from_18,to_18,pos_18,employer_18,project_18,country_18,duties_18,from_19,to_19,pos_19,employer_19,project_19,country_19,duties_19,from_20,to_20,pos_20,employer_20,project_20,country_20,duties_20,employee_id
1,Arcadis consulting,NaN,NaN,NaN,NaN,NaN,2019,Present,HSE Lead,Arcadis Consulting,Construction of Container Terminal 2 in Hamad ...,NaN,Drive the project to start/kick-off (kick-off ...,24-Oct,24-Nov,Sr. HSE Engineer,Arcadis Consulting,Local Roads and Drainage Program (LRDP) and Ro...,NaN,Review contractorâs OHS Plan and MSRA.\nSmal...,13-Jul,14-Sep,HSE Manager,SL Engineering and Contruction (SKEC),Project: Booster Station 132 and enhancements ...,NaN,NaN,11-Jun,13-Jun,Project HSSE Manager,Nael and Bin Harmal Hydroexpert (NBHH),NaN,NaN,Promote and encourage high level of HSE awaren...,9-Nov,11-May,Project HSE Manager,NBHH,Diversion Roads and Villa,NaN,Assist the Project Director in making plans an...,8-Mar,9-Oct,HSE Engineer,NBHH,"Yas Island Development (Pipe Laying, Pumping S...",NaN,Strict monitoring and supervision to all safet...,6-Jan,9-Oct,HSE Officer,NBHH,Construction of TSE Line from Sewerage Treatme...,NaN,Ensures PTW compliance. \nConduct Toolbox Talk...,2-Apr,5-Nov,Project Consultant,Local Government Unit (LGU),Government Sector,NaN,Assess the feasibility of Government projects ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,DORSCH GRUPPE Middle East â Qatar,Qatar / Doha,NaN,Project Manager,NaN,NaN,16-Jun,Till date,Project Manager,DORSCH GRUPPE Middle East â Qatar,ASAS Marina Towers \nMANATEQ Oasis Bldg. Ras B...,NaN,Representing as PMCM Sr. RE with full coordina...,24-Feb,24-Jun,Project Manager,PRIVATE ENGINEERING OFFICE- Qatar,Al Daayen Complex Hall \nAl Wakra Old Souq \nH...,NaN,Leading and directing all construction stages ...,11-Jun,15-Feb,Project Manager,Engineering Consultants Group - Qatar,SAMARIYA Twin Towers: a High rise building loc...,NaN,Leading the project construction planning in e...,10-May,11-May,Resident Engineer,Ehaf Consultancy - Egypt,"Palm Hill City Mall in Cairo, Egypt",NaN,Providing construction input to have an accept...,7-Dec,10-Apr,Resident Engineer / Architect,HAZ INTERNATIONAL â UAE,"Ritz Carlton Hotel Dubai, UAE \nWhite Square O...",NaN,Identify the scope of work and disseminate it ...,2-May,7-Nov,Design Leader,Ewan Consultancy â UAE,"87 Villas & Compound for First Gulf Bank, Abu ...",NaN,Preparing IFC drawings complying with project ...,Oct-97,2-Jan,Architect,AMECO â Egypt,"SOLIMANIA Golf Village, Alex Cairo Road, 1038 ...",NaN,Supervision Site Engineer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,AECOM Middle East Ltd,Qatar,NaN,NaN,NaN,NaN,16-Oct,Present,Senior Planning Engineer,NaN,"LRDP, Contract 02 (Qatar South), QS036\nLRDP, ...",Qatar,Using Primavera P6 Professional for monitoring...,24-Apr,24-Oct,Senior Planning Engineer,NaN,Construction of Residential Compound 70 Villas...,Qatar,Define project scope of work; Established Prel...,11-Aug,14-Apr,Planning Engineer,DIAACONSULT for Engineering & Consulting,SAMA ASWAN Commercial and Residential Complex ...,Egypt,Collect and review the contract documents to d...,7-Dec,11-Aug,Assistant Resident Engineer,DR. M. H. ALI El-SAIE Consulting Engineers,Supply and Installation of 3.3 US MGD SWRO Pl...,UAE,Inspection of civil work at site as per the â...,6-Mar,7-Dec,Project Site Engineer,SPARTAN Trading and Contracting Co,"Holiday Villa Hotels Series on an area of 20,0...",Qatar,Direct and manage the execution of civil work ...,4-Jan,6-Mar,Junior Civil Engineer,Ministry of Transportation,Construction of Arterial Road in East Port Sai...,Egypt,"Reviewing all project documents, drawings, met...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4,"Dorsch Gruppe, Qatar",Qatar,NaN,Sr.Safety Inspector,1,NaN,2021,Till date,Sr.Safety Inspector,"Dorsch Gruppe, Qatar",Roads & Infrastructure in the south of Al-Mesh...,NaN,\n,5-Jul,5-Jul,OHSS Manager,"Al Sarh, Trading & Contracting W.L.L, Qatar",Roads & Infrastructure in the south of Al-Mesh...,NaN,\n,2014,2020,PHSE Engineer/Dy.HSE Manager,"Al Bandary Engineering, Trading & Contracting ...","Sahara tower-P115 (3B+M+38F)-, Al Shahad Tower...",NaN,Reporting to Project manager & D.HSE Corp.Mana...,11-Jun,14-Mar,Sr.Safety Officer/Site In Charge,Power line engineering-Qatar W.L.L,"Viva Baharia (VB20&21)-2P+23+4R+Dome, Pearl Qa...",NaN,\n,11-May,11-Jun,PHSE In Charge,"CEC International Corporation, India","TBM-01, UG-02 project. (Majestic â Chinnasam...",NaN,\n,9-Apr,10-Apr,Sr.Safety Officer,Power line engineering-Qatar W.L.L,"Medina central, Pearl Qatar project, Doha. (8 ...",NaN,\n,2008,2009,Sr.Tunnel Safety Officer,"JT METRO (Kori con. Dubai Branch, UAE",TBM 1-2 Alras Station â Burjuman Station- Du...,NaN,\n,5-Mar,7-Jul,Site Supervisor Cum Safety Supervisor,"Kori construction (S) Pte. Ltd, Singapore","C-823 Circle Stage 2 Project, Paya Lebar Inter...",NaN,\n,4-Mar,5-Feb,Safety Supervisor Cum Lifting Supervisor,"Kori construction (S) Pte. Ltd, Singapore","C-823 Circle Stage 2 Project, Old Airport Road...",NaN,\n,3-Jun,4-Feb,Safety Supervisor,"Kori construction (S) Pte. Ltd, Singapore","824 Circle Stage 1 Project, Nichol Highway sta...",NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,NaN,NaN,NaN,NaN,\n,NaN,\n,3
5,"Dorsch Holding GmbH, Doha, Qatar",NaN,NaN,NaN,NaN,NaN,16-Apr,Present,Senior Planning Engineer,"Dorsch Holding GmbH, Doha, Qatar",Ras Bufontas Special Economic Zone (EQZ01) Con...,Qatar,"Design & Build for Infrastructure, Road Works ...",24-Apr,24-Mar,Lead System Control Engineer,Dar SSH International Engineering Consultants,Project 1: Sabah Al Salem University\nProject...,Kuwait,"Managing all planning, cost control and docume...",9-Feb,14-Feb,Senior Cost/Planning Engineer/ Project Engineer,"Louis Berger, Qatar",\n\n\n,Kuwait,Project 1: Construction Management and Constr...,7-Mar,9-Jan,Project controls / Planning Manager,PROMAN Project Management Company,Kabary city Construction of several high-rise ...,Kuwait,Tracking and handling the project by providing...,6-Feb,7-Feb,Assistance technical office Manager /Acting Pr...,Al-ENMA'A Real Estate Co. Contracting and Main...,Project 1: Housing at East Al-Solibikate\nPro...,Kuwait,Assist in the development and monitoring of co...,3-Jun,6-Jan,Assistance technical Office Manager / Senior P...,Industrial Construction & Engineering Co,Project: Turnkey construction of His Highness...,Qatar,"Preparation, tracking and updating the Master ...",Aug-99,3-May,Assistance technical Office Manager / Structur...,Egyptian Danish Project Management & Construct...,Project 1: Dream Land Housing & Entertainment...,Egypt,Site supervision and quality controlling the d...,Apr-96,Jul-99,Assistance technical Office Manager / Structur...,Arabia International Contracting Co,SIDIKRIR Power Station\n\n\n,Egypt,Preparing the shop drawings & bending list for...,Apr-95,Feb-96,Senior Structural Design Engineer / Structural...,"HAMZA Associates (Consultant Firm),",Project 1: Cairo South Power Station - Water ...,Egypt,Analysis and design of reinforced concrete acc...,Oct-93,Jan-95,Site Engineer,Armed Forces (Military Service),Project: Roads in front of floating bridges a...,Egypt,Check and Approve for the levelling and alignm...,NaN,NaN,NaN,NaN,\n\n\n,NaN,\n\n\n,NaN,NaN,NaN,NaN,\n\n\n,NaN,\n\n\n,NaN,NaN,NaN,NaN,\n\n\n,NaN,\n\n\n,NaN,NaN,NaN,NaN,\n\n\n,NaN,\n\n\n,NaN,NaN,NaN,NaN,\n\n\n,NaN,\n\n\n,NaN,NaN,NaN,NaN,\n\n\n,NaN,\n\n\n,NaN,NaN,NaN,NaN,\n\n\n,NaN,\n\n\n,NaN,NaN,NaN,NaN,\n\n\n,NaN,\n\n\n,NaN,NaN,NaN,NaN,\n\n\n,NaN,\n\n\n,NaN,NaN,NaN,NaN,\n\n\n,NaN,\n\n\n,4

In [71]:
TransactionTimestamps = df_unique.loc[1:DFrows,['employee_name','Date Created','Date Updated']]
missing_columns = df_unique.loc[1:DFrows, ['employee_id']]
TransactionTimestamps = pd.concat([TransactionTimestamps, missing_columns], axis=1)
TransactionTimestamps.head(4)

,employee_name,Date Created,Date Updated,employee_id
1,"Pablo Ageas, Jr.",NaN,NaN,0
2,Waleed Mohamed Saber Mohamed Sarhan,NaN,NaN,1
3,Aly AbdelMonem Abdelhalim,NaN,NaN,2
4,Vijayakumar Sadaiyan,NaN,18-03-2022 at 04:14:20 PM,3

In [72]:
print(panda_data_folder)

C:\Users\Sharmarke.Kadir/Desktop\Panda Data\pythonProject1\.venv

In [73]:
# test_file_path = os.path.join(panda_data_folder, "test_file.txt")
# with open(test_file_path, 'w') as f:
#     f.write("This is a test.")

# print(f"Test file created at: {test_file_path}")


# to see if the path was fine

In [74]:

employeeInformation.to_sql('employeeInformation', con=engine, if_exists='replace', index=False)
employeeEducation.to_sql('employeeEducation', con=engine, if_exists='replace', index=False)
employeeExperience.to_sql('employeeExperience', con=engine, if_exists='replace', index=False)
TransactionTimestamps.to_sql('TransactionTimestamps', con=engine, if_exists='replace', index=False)


print("Data inserted into the database successfully!")

Data inserted into the database successfully!

In [75]:
import pandas as pd
import sqlite3

# Connect to the SQLite database
conn = sqlite3.connect('.venv/mydatabase3.sqlite')  # Update the path accordingly

# Query a specific table, e.g., 'employee_information'
sql = pd.read_sql_query('SELECT * FROM employee_information', conn)

# Display the DataFrame
sql.head()  # Show the first few rows of the DataFrame

# Close the connection
conn.close()

In [76]:
sql.head(10)

,employee_name,years_of_experience,regional_years_of_experience,years_with_dorsch,position,dob,nationality,marital_status,driving_license,languages,employee_id,email,telephone
0,"Pablo Ageas, Jr.",18.0,None,None,Safety Engineer,1979,Filipino,Married,None,"English, Filipino, Arabic, Spanish",0,None,None
1,Waleed Mohamed Saber Mohamed Sarhan,23.0,None,None,Senior Architect,1974,Egyptian,Married,None,Arabic & English,1,None,None
2,Aly AbdelMonem Abdelhalim,16.0,None,None,Senior Planning Engineer,1982,Egyptian,Married,None,Arabic and English,2,None,None
3,Vijayakumar Sadaiyan,19.0,None,None,Senior Safety Inspector,1983,Indian,Married,None,Urdu & english,3,None,None
4,Mohammed Saleh Gomaa,28.0,None,None,Planning Engineer,1970,Egyptian,Married,None,Arabic and English,4,None,None
5,Shahnawaz Pasha,20.0,None,None,Senior Planning Engineer,1976,Indian,Married,None,English,5,None,None
6,Joseph D. Velasco,28.0,None,None,Project Engineer - Civil,5-May,Filipino,Single,None,English,6,None,None
7,Hani Sayed Ibrahim Mostafa,37.0,None,8,Resident Engineer,1963,Egyptian,Married,Yes,Arabic and English,7,None,None
8,Zuhair Younes Al Amour,30.0,None,None,Resident Engineer,None,Syria,None,None,Arabic and English,8,None,None
9,Hesham MOSTAFA MOHAMED IBRAHIM,35.0,None,None,Chief Quantity Surveyor,1961,Egyptian,Married,None,English and Arabic,9,None,None

In [77]:
import streamlit as st

In [84]:
st.write('Hello World')

2024-10-22 16:40:55.151 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-10-22 16:40:55.152 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-10-22 16:40:55.153 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2024-10-22 16:40:55.153 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.